POST http://localhost:4400/employee/register
Content-Type: application/json

{
    "name": "Crispin Manda",
    "email": "crispinmanda06@gmail.com",
    "password": "12345678"
}


### login 
POST http://localhost:4400/employee/login
Content-Type: application/json

{
    "email": "emanuel@yopmail.com",
    "password": "12345678"
}

### fetching employees
GET http://localhost:4400/employee/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6IjU2NDRiNzQ3LTZhMGQtNGE1Yi05YzZjLTI3ZjkyNjJmMjgxNSIsIm5hbWUiOiJDcmlzcGluIE1hbmRhIiwiZW1haWwiOiJjcmlzcGlubWFuZGEwNkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwNSRyUmdzN1RaRmdJV3AzaVJXTEF6T3h1WTNkbzZwZlVmbkRHRnJyMUczWU43NkROcXRhVi5ZMiIsInJvbGUiOiJhZG1pbiIsIndlbGNvbWVkIjp0cnVlLCJpYXQiOjE2OTkxMzIzNjcsImV4cCI6MTY5OTEzNTk2N30.e8lqYIErXS_y4Jz_QgD7DO2sMDKjn4WF_gEKOQUvPuw


### checking user details
GET http://localhost:4400/employee/check_user_details
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6IjU2NDRiNzQ3LTZhMGQtNGE1Yi05YzZjLTI3ZjkyNjJmMjgxNSIsIm5hbWUiOiJDcmlzcGluIE1hbmRhIiwiZW1haWwiOiJjcmlzcGlubWFuZGEwNkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwNSRyUmdzN1RaRmdJV3AzaVJXTEF6T3h1WTNkbzZwZlVmbkRHRnJyMUczWU43NkROcXRhVi5ZMiIsInJvbGUiOiJhZG1pbiIsIndlbGNvbWVkIjp0cnVlLCJpYXQiOjE2OTkxMzIzNjcsImV4cCI6MTY5OTEzNTk2N30.e8lqYIErXS_y4Jz_QgD7DO2sMDKjn4WF_gEKOQUvPuw


### assign user Project
POST http://localhost:4400/projects/assignProject
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6IjU2NDRiNzQ3LTZhMGQtNGE1Yi05YzZjLTI3ZjkyNjJmMjgxNSIsIm5hbWUiOiJDcmlzcGluIE1hbmRhIiwiZW1haWwiOiJjcmlzcGlubWFuZGEwNkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwNSRyUmdzN1RaRmdJV3AzaVJXTEF6T3h1WTNkbzZwZlVmbkRHRnJyMUczWU43NkROcXRhVi5ZMiIsInJvbGUiOiJhZG1pbiIsIndlbGNvbWVkIjp0cnVlLCJpYXQiOjE2OTkxMzA0ODIsImV4cCI6MTY5OTEzNDA4Mn0.Uqhtchx4Qw6OaiQICFc-tCgf8tUn6LG7R-Nrxf4t-ZQ

{
    "projectId":"1",
    "userId":"4"
}

//CHECKING COMPLETE PROJECTS
###
POST http://localhost:4400/projects/completeProjects
Content-Type: application/json

# CHECKING PENDING PROJECTS
###
POST http://localhost:4400/projects/pendingProjects
Content-Type: application/json

//CHECKUSER
###
GET http://localhost:4400/projects/check
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6IjU2NDRiNzQ3LTZhMGQtNGE1Yi05YzZjLTI3ZjkyNjJmMjgxNSIsIm5hbWUiOiJDcmlzcGluIE1hbmRhIiwiZW1haWwiOiJjcmlzcGlubWFuZGEwNkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwNSRyUmdzN1RaRmdJV3AzaVJXTEF6T3h1WTNkbzZwZlVmbkRHRnJyMUczWU43NkROcXRhVi5ZMiIsInJvbGUiOiJhZG1pbiIsIndlbGNvbWVkIjp0cnVlLCJpYXQiOjE2OTkxMzE1NjgsImV4cCI6MTY5OTEzNTE2OH0.wgIJPAoJ00CuGVcMWYhZ_6V0ilui_6qnwj_tQXGN5Ow


## CHECK ASSIGNED PROJECT
###
# GET http://localhost:4400/projects/assigned-projects
# Content-Type: application/json
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6Ijc5OWRiY2Q4LWE2ZjUtNDQwZC05MjlkLTBhMDE2YWIwMjAzMSIsIm5hbWUiOiJFbW1hbnVlbCBLcCIsImVtYWlsIjoiZW1hbnVlbEB5b3BtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JFkwUTFhWVJXMGNDcmx1ZWJMSGFuUy51MW5XTWxLLmpmeVp3NjVMV1IvVTVGeTk4M0ZuSWdHIiwicm9sZSI6ImVtcGxveWVlIiwid2VsY29tZWQiOmZhbHNlLCJpYXQiOjE2OTkxMzUzODksImV4cCI6MTY5OTEzODk4OX0.I2GDHc_Yzip5o7fHiYM7yuN5jLfX8JgZn_EmLVC0pxk

